
name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  SPOONACULAR_API_KEY: asdlfkj

jobs:

  client-tests:
    runs-on: ${{ matrix.os }}
    env:
      MONGODB_URL: mongodb://127.0.0.1:27017/test
      working-directory: ./client
    strategy:
      fail-fast: false
      matrix:
        node: ['12', '14', '16']
        os: [ubuntu-latest]

    services:
          mongodb:
              image: mongo
              env:
                MONGO_INITDB_ROOT_USERNAME: test
                MONGO_INITDB_ROOT_PASSWORD: password
                MONGO_INITDB_DATABASE: test
              options: >-
                --health-cmd mongo
                --health-interval 10s
                --health-timeout 5s
                --health-retries 5
              ports:
                - 27017:27017

    name: Node ${{ matrix.node }} on ${{ matrix.os }}
    steps:
      - name: ♻️ Check out Git Repository
        uses: actions/checkout@v2

      - name: 🔖  Set up Node
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}

      - name: ⬇️  Install npm dependencies
        working-directory: ${{env.working-directory}}
        run: npm install

      - name: ✅  Run tests
        working-directory: ${{env.working-directory}}
        run: npm run test

      - name: 🔴 Lint all files
        working-directory: ${{env.working-directory}}
        run: npm run lint:check

  server-tests:
    runs-on: ${{ matrix.os }}
    env:
      working-directory: ./server
    strategy:
      fail-fast: false
      matrix:
        node: ['12', '14', '16']
        os: [ubuntu-latest]

    name: Node ${{ matrix.node }} on ${{ matrix.os }}
    steps:
      - name: ♻️ Check out Git Repository
        uses: actions/checkout@v2

      - name: 🔖  Set up Node
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}

      - name: ⬇️  Install npm dependencies
        working-directory: ${{env.working-directory}}
        run: npm install

      # - name: ✅  Run tests
      #   working-directory: ${{env.working-directory}}
      #   run: npm run test

      - name: 🔴 Lint all files
        working-directory: ${{env.working-directory}}
        run: npm run lint:check